# /etc/pip-kiosk/pip.conf

# The Unique ID of this machine - automatically assigned during installation (install_pip.sh)
PIP_ID=change_me

# The URL to display 
# Set by install_pip.sh. Example:
# https://carrismetropolitana.pt/pips?stop_ids=090141%2C090142&pip_id=123&scale=1.2
TARGET_URL="change_me"

# Monitoring/Heartbeat URL
# logic will append ?pip_id=$PIP_ID
MONITOR_URL="https://status.carrismetropolitana.pt/api/push/A5lHSdIB3CSzXQVUpSGWlG5JuaP3RGqC"

# Interval in seconds for the heartbeat
PING_INTERVAL=30