# /etc/pip-kiosk/pip.conf

# The Unique ID of this machine - automatically assigned during installation (install_pip.sh)
PIP_ID=change_me

# The URL to display 
# CHANGE THIS to something like https://carrismetropolitana.pt/pips?pip_id=PIP_ID and make the redirects 
TARGET_URL="https://carrismetropolitana.pt/pips?stop_ids=100013%2C100027&max_lines=5"

# Monitoring/Heartbeat URL
# logic will append ?pip_id=$PIP_ID
MONITOR_URL="https://status.carrismetropolitana.pt/api/push/A5lHSdIB3CSzXQVUpSGWlG5JuaP3RGqC"

# Interval in seconds for the heartbeat
PING_INTERVAL=30